#!/bin/bash

# this is a simple config for herbstluftwm

#source ~/.colors
# test command to make the terminal pretty
xrdb ~/.Xresources
# begin all the herbstluftwm stuff

hc() {
    herbstclient "$@"
}

hc unrule -F

hc emit_hook reload

xsetroot -solid '#5A8E3A'


# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

#define and set up the tags
TAG_NAMES=( 1 2 3 4 5 6 )
TAG_KEYS=( {1..6} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# cycle through tags
hc keybind $Mod-bracketright use_index +1 --skip-visible
hc keybind $Mod-bracketleft  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
#hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

### Custom Keybindings

#Backlight control

#increase
hc keybind $Mod-F7 spawn ~/.config/herbstluftwm/backlight.sh inc 5
#decrease
hc keybind $Mod-F6 spawn ~/.config/herbstluftwm/backlight.sh dec 5

#Volume Control
#up
hc keybind $Mod-F10 spawn ~/.config/herbstluftwm/volume.sh up 2
#down
hc keybind $Mod-F9 spawn ~/.config/herbstluftwm/volume.sh down 2
#mute
hc keybind $Mod-F8 spawn ~/.config/herbstluftwm/volume.sh mute

#Frequently Used Programs
hc keybind $Mod-Shift-f spawn firefox

hc keybind $Mod-d spawn ~/.config/herbstluftwm/dmenu.sh

#background changing
hc keybind $Mod-Shift-b spawn ~/.config/herbstluftwm/wp change

#Screen shots
hc keybind $Mod-Print spawn ~/.config/herbstluftwm/screenshot.sh

#Changing the padding
hc keybind $Mod-p spawn ~/.config/herbstluftwm/padding.sh

#Add a key for quick suspend
#hc keybind XF86Launch1 spawn ~/.config/herbstluftwm/suspend.sh

#Restart the systemd module for netctl-auto
hc keybind $Mod-Shift-i spawn ~/.config/herbstluftwm/internet_restart.sh
# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color 'orange'
hc set frame_border_normal_color 'red'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 5

hc attr theme.active.color 'orange'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#000000'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set default frame layout 2

hc set_layout horizontal

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# set the background and apply the colorscheme
#~/.config/herbstluftwm/wp change AuroraOverIceland.png
#~/.config/herbstluftwm/wp change fubuki.png
#~/.config/herbstluftwm/wp change manhatten.png
#~/.config/herbstluftwm/wp change windwaker.jpg
#~/.config/herbstluftwm/wp change theater_17.jpg
#~/.config/herbstluftwm/wp change Tokyo-Subway-Map-Dark.jpg
#~/.config/herbstluftwm/wp change hexagons.jpg
#~/.config/herbstluftwm/wp change reigen.jpg
~/.config/herbstluftwm/wp change winter_fun.jpg
#~/.config/herbstluftwm/wp change megumin.jpg
#~/.config/herbstluftwm/wp change botw.png




# start the top status bar
#~/.config/herbstluftwm/runbar.sh

# start the battery notification script
#~/.config/herbstluftwm/batterynotification.sh

#dunst&

# find the panel
panel=~/.config/herbstluftwm/runbar.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
